const PREFIX = 'BROWSER/';
export const SET_DEVICE_TYPE = `${PREFIX}SET_DEVICE_TYPE`;
export const BROWSE_SERVER = `${PREFIX}BROWSE_SERVER`;
export const BROWSED_CONTENT = `${PREFIX}BROWSED_CONTENT`;
export const SELECT_CONTENT_NODE = `${PREFIX}SELECT_CONTENT_NODE`;
