export const symbols = {
  audio: '🎧',
  browser: '𝄙',
  controls: '🕹',
  clear: '🗌',
  close: '✖',
  computer: '🖳',
  network: '🖧',
  playlist: '⬱',
  remove: '⮿',
  server: '🖥',
  video: '📼',
  vlc: '👽',
  play: '▶',
  playing: '...',
  pause: '⏸',
  next: '⏭',
  previous: '⏮',
};
