const PREFIX = 'PLEX/';
export const FIND_MEDIA_SERVERS = `${PREFIX}FIND_MEDIA_SERVERS`;
export const FOUND_MEDIA_SERVERS = `${PREFIX}FOUND_MEDIA_SERVERS`;
export const SELECT_MEDIA_SERVER = `${PREFIX}SELECT_MEDIA_SERVER`;
export const BROWSE_SERVER = `${PREFIX}BROWSE_SERVER`;
export const BROWSED_CONTENT = `${PREFIX}BROWSED_CONTENT`;
export const SELECT_CONTENT_NODE = `${PREFIX}SELECT_CONTENT_NODE`;
